group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [

    path('',views.ListGroup.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('groupdetail/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinView.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveView.as_view(),name='leave'),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [

        path('',views.PostListView.as_view(),name='post'),
        path('<slug:slug>/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
        path('createpost/',views.CreatePostView.as_view(),name='createPost'),
        path('delete/<int:pk>/',views.DeletePostView.as_view(),name='delete'),
        path('by/<slug:username>/',views.UserPost.as_view(),name='for_user')
]

social/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home'),
    path('account/',include('account.urls',namespace='account')),
    path('group/',include('group.urls',namespace='group')),
    path('posts/',include('posts.urls',namespace='posts')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

group/models.py
from django import template
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse
from django.db import models

# Create your models here.

register = template.Library()
User = get_user_model()

class Group(models.Model):
    name = models.CharField(max_length=50,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    member = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('group:all')

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='membership',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='group_users',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    class Meta:
        unique_together = ['group', 'user']

group/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

# Create your views here.
from django.views.generic import CreateView, DetailView, ListView, RedirectView

from .models import Group, GroupMember


class CreateGroup(CreateView,LoginRequiredMixin):
    model = Group
    fields = ['name','description']

class SingleGroup(DetailView):
    model = Group

class ListGroup(ListView):
    model = Group
    paginate_by = 1

class JoinView(LoginRequiredMixin,RedirectView):
    login_url = 'account:login'
    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,*args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            print("already joined")
        else:
            pass
        return super().get(self.request,*args,**kwargs)

class LeaveView(LoginRequiredMixin,RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMember.objects.filter(user = self.request.user,group__slug = self.kwargs.get('slug'))
        except GroupMember.DoesNotExist:
            print("Such a relation does not exist")
        else:
            membership.delete()
        return super().get(self,request,*args,**kwargs)

group/templates/group/group_base.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            {% block pregroup %}


            {% endblock pregroup %}
        {% block group_content %}

        {% endblock group_content %}

        {% block post_group %}

        {% endblock post_group %}

        </div>
    </div>

{% endblock %}

group/templates/group/group_detail.html
{% extends "group/group_base.html" %}

{% block title %}
    Group Detail
{% endblock title %}

{% block pregroup %}
    <div class="col-md-4 p-3">
    <h2 class="display-4"> {{ group.name }}</h2>
    <h5>Memeber Count:{{ group.member.count }}</h5>



    <div class="content">
    {% if user in group.member.all %}
        <a href="{% url 'group:leave' slug=group.slug %}" class="btn btn-warning text-light btn-block">Leave</a>

     {% else %}
        <a href="{% url 'group:join' slug=group.slug %}" class="btn btn-primary btn-block">Join</a>
    {% endif %}

    </div>
    </div>

{% endblock pregroup %}


{% block group_content %}
    <div class="col-md-8 p-4">
    {% if group.posts.count == 0 %}
    <h2>No Post yet in this program</h2>
        {% else %}
        <div class="media">
            <div class="media-body">
            {% for post in group.posts.all %}
                {% include "posts/_single_post.html" %}
            {% endfor %}
            </div>
        </div>
    {% endif %}


    </div>


{% endblock group_content %}

group/templates/group/group_form.html
{% extends 'group/group_base.html' %}

{% load bootstrap4 %}

{% block title %}
Create New Group
{% endblock title %}

{% block group_content %}
<h4>Create Group</h4>
<form action="{% url 'group:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-primary">

</form>
{% endblock group_content %}

group/templates/group/group_list.html
{% extends "group/group_base.html" %}

{% block title %}
List of groups
{% endblock title %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
    {% if user.is_authenticated %}
    <h2>welcome <a href="{% url 'posts:for_user' username=user.username %}" >@{{user.username}}</a></h2>
    {% endif %}
    <p>Welcome to the groups page! Select a Group with a shared interest!</p>
</div>

    {% if user.is_authenticated %}
    <a href="{% url 'group:create' %}" class="btn btn-lg btn-warning text-light"><i class="fa fa-plus"></i> Create New Group</a>
    {% endif %}
</div>
{% endblock pregroup %}

{% block group_content %}
<div class="col-md-8">
    <h2 class="text-center bg-secondary text-light py-2">Groups</h2>
    {% if group_list.count == 0 %}
    <h3>No groups</h3>
    {% endif %}
<ul class="list-group">
{% for group in group_list %}
  <li class="list-group-item" aria-disabled="true">
    <a href="{% url 'group:single' slug=group.slug %}"><h3 class='title'>{{group.name}}</h3></a>
        <div class="container-fluid">
            {{group.description|safe}}
        </div>
    </li>
  <li class="list-group-item">
    <div class="row">
        <div class="col-md-4">
            <span class="badge">{{group.member.count}}</span>member{{group.members.count|pluralize}}
        </div>
         <div class="col-md-4">
            <span class="badge">{{group.posts.count}}</span>post{{group.posts.count|pluralize}}
        </div>
    </div>
  </li>
  <br>
{% endfor %}
</ul>
</div>
{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/group?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/group?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
{% endblock group_content %}