account/urls.py
from django.urls import path, include
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('signup',views.SignUp.as_view(),name='signup'),
    path('login/',views.logIn,name='login'),
    path('logout/',views.logOut,name='logout'),
]

group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [

    path('',views.ListGroup.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('groupdetail/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinView.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveView.as_view(),name='leave'),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [

        path('',views.PostListView.as_view(),name='post'),
        path('<slug:slug>/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
        path('createpost/',views.CreatePostView.as_view(),name='createPost'),
        path('delete/<int:pk>/',views.DeletePostView.as_view(),name='delete'),
        path('by/<slug:username>/',views.UserPost.as_view(),name='for_user')
]

social/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home'),
    path('account/',include('account.urls',namespace='account')),
    path('group/',include('group.urls',namespace='group')),
    path('posts/',include('posts.urls',namespace='posts')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/_alert.html
{% if messages %}
    {% for message in messages %}
    <div id="message" class="container">
        <div class="alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            </button>
            <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                Error:
                {% else %}
                {{message.tags|title}}
                {% endif %}
            </strong>
            {{message}}
        </div>
    </div>
    {% endfor %}
{% endif %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:createPost' %}">Create post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'group:create' %}">Create Group</a>
             </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}" tabindex="-1" aria-disabled="true">Log out </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">Login</a>
          </li>

        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'group:all' %}">Groups</a>
          </li>
    </ul>
  </div>
</nav>
<div class="container">
    {% block content %}

{% endblock %}
</div>

    <script src="{% static 'social/js/lib/jquery.min.js'%}"></script>
    <script src="{% static 'social/js/lib/popper.min.js'%}"></script>
    <script src="{% static 'social/js/lib/bootstrap.min.js'%}"></script>
    <script src="{% static 'social/js/script.js'%}"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% include "_alert.html" %}
{% endblock %}