group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [

    path('',views.ListGroup.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('groupdetail/<slug:slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>',views.JoinView.as_view(),name='join'),
    path('leave/<slug:slug>',views.LeaveView.as_view(),name='leave'),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [

        path('',views.PostListView.as_view(),name='post'),
        path('<slug:slug>/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
        path('createpost/',views.CreatePostView.as_view(),name='createPost'),
        path('delete/<int:pk>/',views.DeletePostView.as_view(),name='delete'),
        path('by/<slug:username>/',views.UserPost.as_view(),name='for_user')
]

social/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home'),
    path('account/',include('account.urls',namespace='account')),
    path('group/',include('group.urls',namespace='group')),
    path('posts/',include('posts.urls',namespace='posts')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

posts/models.py
from django.db import models
from group.models import Group
from django.urls import reverse
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Group,related_name='posts',on_delete=models.CASCADE)
    img = models.ImageField(upload_to="photo/%Y/%m/%d/",blank=True)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('group:single',kwargs={'slug':self.group.slug})

    class Meta:
        ordering = ['-created_at']
        # unique_together = ['user','message']

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'group', 'img']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for visible in self.visible_fields():
            visible.label = ''
            visible.field.widget.attrs['placeholder'] = visible.name

posts/views.py
from braces.views import SelectRelatedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.http import Http404
from django.views.generic import ListView,DetailView,CreateView,DeleteView
from .models import Post, User
from .forms import PostForm
from django.contrib.auth import get_user_model
from group.models import Group,GroupMember
# Create your views here.


class PostListView(SelectRelatedMixin,ListView):
    model = Post
    select_related = ('user','group')

class PostDetailView(SelectRelatedMixin,DetailView):
    model = Post
    select_related = ('user','group')


class CreatePostView(LoginRequiredMixin,SelectRelatedMixin,CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = self.request.user
        group = self.object.group
        isMember = GroupMember.objects.get(group=group,user=user)
        if isMember:
            self.object.user = user
            self.object.save()
            return super().form_valid(form)
        else:
            return HttpResponseRedirect(reverse('group:all'))


class DeletePostView(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = 'group:single'

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        user = self.object.user
        group = self.object.group
        isMember = GroupMember.objects.get(group=group, user=user)
        if not isMember:
            return HttpResponseRedirect(reverse_lazy(self.success_url, kwargs={'slug': group.slug}))
        self.object.delete()
        return HttpResponseRedirect(reverse_lazy(self.success_url, kwargs={'slug': group.slug}))


class UserPost(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404

        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

posts/templates/posts/_single_post.html
<blockquote class="blockquote">
<p class="mb-0">{{ post.message }}</p>
<a href="{% url 'posts:post_detail' pk=post.pk slug=post.group.slug %}">Go to post</a>
<footer class="blockquote-footer">Created by: <a href="#">@{{ post.user.username }}</a> at <cite title="Source Title"><a href="#">{{ post.created_at }}</a></cite>
    {% if post.group %}
in <a href="#">{{ post.group.name }}</a>
{% endif %}</footer>
</blockquote>

<div class="media-footer">
{% if user.is_authenticated and post.user == user and not hide_delete %}
    <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple text-danger">
    <i class="fa fa-times" aria-hidden="true"></i>Delete</a>
{% endif %}
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
    <div class="row">
    {% block prepost %}
    
    {% endblock prepost %}

    {% block post_content %}
    
    {% endblock post_content %}

    {% block post_post %}
    
    {% endblock post_post %}
    </div>
</div>
{% endblock content %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block title %}
Confirm delete
{% endblock title %}

{% block post_content %}
<h3> Are you sure want to delete this post?</h3>
<div class="posts">
    {% include "posts/_single_post.html" with post=object hide_delete=True %}
</div>
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<button type="submit" class="btn btn-danger">Confirm Delete</button>
</form>
{% endblock post_content %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% load staticfiles %}

{% block title %}
post detail
{% endblock %}

{% block post_content%}
<div class="col-md-8">
{% include "posts/_single_post.html" %}
</div>
<img src="{{ post.img.url }}" alt="" height="50px" width="200px">
{% endblock post_content %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Send Post</button>
    </form>

{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
 <h5>This is the post list page</h5>
    {% for i in post_list %}
        {{ i }}
    {% endfor %}
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block title %}
Post List
{% endblock title %}

{% block prepost %}
<div class="col-md-4">
    <h2>@{{ post_user.username }}</h2>
</div>
{% endblock prepost %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
    {% include "posts/_single_post.html" %}
    {% endfor %}
</div>
{% endblock post_content %}